#######################################################################################
# Autogit - Config and deploy hooks                                                   #
#######################################################################################
# This YAML file should be present in the root folder of your codebase               #
#######################################################################################

# Hooks are Bash scripts executed at different stages during deployment.
# Arguments: $1 = branch, $2 = commit id, $3 = checkout folder

hooks:
  # SETUP: Create folder structure for the newest release
  setup_before: |
    echo "Setting up folder structure for the new release"
    mkdir -p /data/sites/web/kjanivaneenaemebe/www

  setup_after: |
    echo "Setup completed for the new release"
    exit 0

  # INSTALL: Put the code in the release folder
  install_before: |
    echo "Preparing for installation"
    cd /data/sites/web/kjanivaneenaemebe/www

  install_after: |
    echo "Code installed in the release folder"
    exit 0

  # SHAREDSYMLINK: Create symlinks for shared files and folders
  sharedsymlink_before: |
    echo "Creating symlinks for shared files and folders"
    ln -s /data/sites/web/kjanivaneenaemebe/shared/config.yml /data/sites/web/kjanivaneenaemebe/www/config.yml

  sharedsymlink_after: |
    echo "Symlinks created for shared files and folders"
    exit 0

  # SYMLINK: Set the current symlink to the newest release
  symlink_before: |
    echo "Setting current symlink to the newest release"
    ln -sfn /data/sites/web/kjanivaneenaemebe/www /data/sites/web/kjanivaneenaemebe/current

  symlink_after: |
    echo "Symlink to the newest release set"
    exit 0

  # CLEANUP: Cleanup old releases, keeping two most recent releases
  cleanup_before: |
    echo "Cleaning up old releases"
    cd /data/sites/web/kjanivaneenaemebe/
    ls -t | grep -E 'release-' | tail -n +3 | xargs rm -rf

  cleanup_after: |
    echo "Old releases cleaned up"
    exit 0

# Shared folders: These are the folders you want to persist across releases (e.g., uploads, media)
shared_folders:
  - /data/sites/web/kjanivaneenaemebe/www/img
  - /data/sites/web/kjanivaneenaemebe/www/js
  - /data/sites/web/kjanivaneenaemebe/www/css
  - /data/sites/web/kjanivaneenaemebe/www/media

# Shared files: These are the configuration files you want to persist across releases
shared_files:
  - /data/sites/web/kjanivaneenaemebe/config.yml
